=== anechka396/finaltask/LikeIt/src/main/resources/commandSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.tc.by/commands"
           xmlns:tns="http://www.epam.tc.by/commands">

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="class" type="tns:ClassNameType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="base" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ClassNameType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="command" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== anechka396/finaltask/LikeIt/src/main/resources/command.xml
<?xml version="1.0" encoding="utf-8"?>
<tc:config base="by.epam.likeit.command.impl"
           xmlns:tc="http://www.epam.tc.by/commands"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.epam.tc.by/commands commandSchema.xsd">
    <class>
        <name>LoginCommand</name>
        <command>login</command>
    </class>
    <class>
        <name>LogoutCommand</name>
        <command>logout</command>
    </class>
    <class>
        <name>RegistrationCommand</name>
        <command>registration</command>
    </class>
    <class>
        <name>ChangeLocaleCommand</name>
        <command>locale</command>
    </class>
    <class>
        <name>GetLastQuestionsCommand</name>
        <command>last</command>
    </class>
    <class>
        <name>AddQuestionCommand</name>
        <command>add-question</command>
    </class>
    <class>
        <name>GetAllTopicsCommand</name>
        <command>all-topics</command>
    </class>
    <class>
        <name>DeleteQuestionCommand</name>
        <command>delete-question</command>
    </class>
    <class>
        <name>GetQuestionAndAnswersCommand</name>
        <command>get-question</command>
    </class>
    <class>
        <name>AddAnswerToQuestionCommand</name>
        <command>add-answer</command>
    </class>
    <class>
        <name>DeleteAnswerCommand</name>
        <command>delete-answer</command>
    </class>
    <class>
        <name>SetRatingCommand</name>
        <command>set-rating</command>
    </class>
    <class>
        <name>EditQuestionCommand</name>
        <command>edit-question</command>
    </class>
    <class>
        <name>GetUserRatingCommand</name>
        <command>get-user-rating</command>
    </class>
    <class>
        <name>ChangePasswordCommand</name>
        <command>change-password</command>
    </class>
    <class>
        <name>ChangeImageCommand</name>
        <command>change-image</command>
    </class>
    <class>
        <name>EditUserProfileCommand</name>
        <command>edit-profile</command>
    </class>
    <class>
        <name>AddTopicCommand</name>
        <command>add-topic</command>
    </class>
    <class>
        <name>EditTopicCommand</name>
        <command>edit-topic</command>
    </class>
    <class>
        <name>DeleteTopicCommand</name>
        <command>delete-topic</command>
    </class>
</tc:config>
